import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { IUploadFile } from 'src/app/interfaces/printer.interface';
import { PrinterService } from 'src/app/services/printer-roccia/printer.service';
import { AdministrativeRequestService } from 'src/app/services/vposuniversal/administrative-request.service';
import { VposerrorsService } from 'src/app/services/vposuniversal/vposerrors.service';
import Swal, { SweetAlertResult } from 'sweetalert2';

@Component({
  selector: 'app-administrative-module',
  templateUrl: './administrative-module.component.html',
  styleUrls: ['./administrative-module.component.scss'],
})
export class AdministrativeModuleComponent implements OnInit {

  @Input() userData: string = '';
  @Output() showAnulationModal = new EventEmitter<boolean>();

  public ci_transaction: string = '';
  public numSeq_transaction: string = '';

  // Asegúrate de definir la plantilla HTML como una propiedad de la clase
  // Usamos 'readonly' y 'public' o 'private' según necesites
  private readonly twoFactorAuthHtml: string = `
    <div class="swal-custom-container">
        <p class="instruction-text">
            Enter below the 6-digit authentication code generated by your app:
        </p>
        <div class="otp-inputs-container">
            <input type="text" id="otp-1" maxlength="1" class="otp-input swal2-input" data-next="otp-2">
            <input type="text" id="otp-2" maxlength="1" class="otp-input swal2-input" data-next="otp-3" data-prev="otp-1">
            <input type="text" id="otp-3" maxlength="1" class="otp-input swal2-input" data-next="otp-4" data-prev="otp-2">
            <input type="text" id="otp-4" maxlength="1" class="otp-input swal2-input" data-next="otp-5" data-prev="otp-3">
            <input type="text" id="otp-5" maxlength="1" class="otp-input swal2-input" data-next="otp-6" data-prev="otp-4">
            <input type="text" id="otp-6" maxlength="1" class="otp-input swal2-input" data-prev="otp-5">
        </div>

        <div class="separator">OR</div>

        <div class="backup-section">
            <p class="instruction-text small-text">
                If you have no longer access to the authentication app, you can use one of the back-up codes if you have them.
            </p>
            <input type="text" id="backup-code-input" class="backup-code-input swal2-input" placeholder="Enter the back-up code here">
        </div>
    </div>
    `;

  constructor(
    private _adminAction: AdministrativeRequestService,
    private _errorsvpos: VposerrorsService,
    private _printer: PrinterService,
  ) { }

  ngOnInit(): void {
  }

  public async administrativeMode(option: number){

    Swal.fire({
      title: '¿Está seguro de que desea realizar esta acción?',
      text: 'Esta acción no se puede deshacer',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Si, estoy seguro',
      cancelButtonText: 'Cancelar',
    }).then(async (result) => {
      if (result.isConfirmed) {
        const macAddres: string = await this.getMacAddress();

        switch (option) {
          case 1:
            await this.showTwoFactorAuthSwal()
            // await this.pre_closeBox(macAddres)
            // .then((res) => {
            //   this.ShowDiologSuccess(res);
            // })
            // .catch((err) => {
            //   this.ShowDiologError(err);
            // });
            break;
          case 2:
            await this.closeBox(macAddres)
            .then((res) => {
              this.ShowDiologSuccess(res);
            })
            .catch((err) => {
              this.ShowDiologError(err);
            });
            break;
          // case 3:
          //   await this.anulateTransaction(macAddres)
          //   .then((res) => {
          //     this.ShowDiologSuccess(res);
          //   })
          //   .catch((err) => {
          //     this.ShowDiologError(err);
          //   });
          //   break;
          default:
            // Opcional: Manejar valores inesperados
            console.warn(`Opción ${option} no reconocida`);
            break;
        }
      }
    });

  }

  /**
   * To pre-close box
   * @returns
   */
  public async pre_closeBox(macAddress: string) {
    try {

      let dataRes: any;

      console.log('in pre_closeBox');

      const responseJSON: any = await this._adminAction.pre_closeCashRegister(this.userData, macAddress);

      console.log('responseJSON', responseJSON.data);

      if (responseJSON.data.datavpos.codRespuesta === '00') {
        const dataReq: IUploadFile = {
          pathRoute: responseJSON.data.datavpos.nombreVoucher,
          register: macAddress,
          typeFile: false,
          adminFile: true,
        };

        console.log('dataReq', dataReq);

        dataRes = await this._printer.uploadFile(dataReq);

        console.log('UPLOAD FILE', dataRes.message);
      }

      const dataReturn: any = {
        datavpos: responseJSON.data.datavpos,
        uploadFile: dataRes.data
      };

      console.log('RETURN DATA', dataReturn);

      // creo que esto va entre paréntesis
      return dataReturn
    } catch (error: any) {
      console.error(error);
      throw new Error(error);
    }

  }

  /**
   * To close box
   * @returns
   */
  public async closeBox(macAddress: string) {
    try {
      let dataRes: any;

      console.log('in CloseBox');

      const responseJSON: any = await this._adminAction.closeCashRegister(
        this.userData,
        macAddress
      );

      console.log('responseJSON', responseJSON['data']);

      if (responseJSON.data.datavpos.codRespuesta === '00') {
        const dataReq: IUploadFile = {
          pathRoute: responseJSON.data.datavpos.nombreVoucher,
          register: macAddress,
          typeFile: true,
          adminFile: true,
        };

        dataRes = await this._printer.uploadFile(dataReq);

        console.log('UPLOAD FILE', dataRes['message']);
      }

      const dataReturn: any = {
        closeBox: responseJSON.data.datavpos,
        uploadFile: dataRes.data
      };

      console.log('RETURN DATA', dataReturn);

      return dataReturn

    } catch (error: any) {
      console.error(error);
      throw new Error(error);
    }

  }

  /**
   * To show modal to anulate transaction
   * @returns ci, numSeq
   */
  public async showAnulateTransactionModal(): Promise<void | string> {
     this.showAnulationModal.emit(true);
  }

  /**
   * To anulate transaction
   * @returns
   */
  // public async anulateTransaction(macAddress: string) {
  //   //
  //   try {

  //     const responseJSON = await this._adminAction.anulationPayment(this.ci_transaction, this.numSeq_transaction, macAddress);

  //     console.log('responseJSON', responseJSON);

  //     return responseJSON;

  //   } catch (error) {
  //     console.error(error)

  //     return `error: ${error}`;
  //   }
  // }

  /**
   * Function to get the current MAC-ADDRESS
   * @param type Type of string
   */
  public async getMacAddress(){

    const macaddress: string = await this._printer.getMacAddress();

    console.log('macaddress', macaddress);

    return macaddress;
  }

  private ShowDiologSuccess(dataRes: any){
    console.log('dataRes', dataRes);
    const responseCode = dataRes.datavpos.codRespuesta;
    const message = this._errorsvpos.getErrorMessageCode(responseCode);


    // 2. Handle success case (code '00')
    if (responseCode === '00') {
      // this.generarPDF().catch(console.error); // Generate PDF async

      Swal.fire({
        icon: 'success',
        title: 'Acción realizada exitosamente\n'+message,
        showConfirmButton: false,
        allowOutsideClick: false,
        timer: 4000, // El modal se cerrará después de 5 segundos
      });
    }
    // 3. Handle other cases
    else {

      Swal.fire({
        icon: 'warning',
        title: 'Solicitud no procesada.\n'+message,
        showConfirmButton: false,
        allowOutsideClick: false,
        timer: 4000,
        // didClose: () => resolve()
      });
    }
  }

  private ShowDiologError(dataErr: any){
    // 4. Handle request errors
    let _messageError: string = 'Ha ocurrido un error.';
    let timeShow: number = 4000;

    // if (this.dni?.value === "90000000") {
    //   _messageError = 'Muestrele este error a un técnico \n Error: '+(error instanceof Error ? error.message : 'Desconocido');
    //   timeShow = 6000;
    // }

    Swal.fire({
      icon: 'error',
      title: _messageError +'\n'+ dataErr.message,
      showConfirmButton: false,
      allowOutsideClick: false,
      timer: timeShow,
      // didClose: () => resolve()
    });
  }

  /**
   * Muestra el modal de Autenticación de Dos Pasos con SweetAlert2.
   * La función está correctamente tipada en TypeScript.
   */
  private async showTwoFactorAuthSwal(): Promise<void> {
    // Definición de la estructura de datos que devuelve preConfirm
    interface AuthResult {
      code: string;
      type: 'otp' | 'backup';
    }

    Swal.fire<AuthResult>({
      title: 'Two Step Authentication',
      html: this.twoFactorAuthHtml, // Usamos la plantilla HTML de la clase
      icon: undefined,
      showCancelButton: true,
      confirmButtonText: 'Verify',
      cancelButtonText: 'Cancel',
      focusConfirm: false,
      allowOutsideClick: false,
      customClass: {
        container: 'swal2-container-custom',
        popup: 'auth-modal-popup',
        confirmButton: 'btn btn-primary',
        cancelButton: 'btn btn-secondary',
      },

      // --- didOpen: Lógica de inicialización y manejo de eventos del DOM ---
      didOpen: () => {
        // Tipar los elementos del DOM de forma estricta
        const inputs: NodeListOf<HTMLInputElement> = document.querySelectorAll('.otp-input');
        const backupInput: HTMLInputElement | null = document.getElementById('backup-code-input') as HTMLInputElement;
        const firstInput: HTMLInputElement | null = document.getElementById('otp-1') as HTMLInputElement;

        // 1. Lógica para saltar entre inputs OTP
        inputs.forEach(input => {
          input.addEventListener('keyup', (e: KeyboardEvent) => {
            const currentInput = e.target as HTMLInputElement;
            const val = currentInput.value;

            // Salto al siguiente input (si se ingresa un dígito)
            if (val.length === 1 && currentInput.dataset['next']) {
              (document.getElementById(currentInput.dataset['next']) as HTMLInputElement)?.focus();
            }
            // Salto al anterior (si se presiona Backspace y el campo está vacío)
            else if (e.key === 'Backspace' && val.length === 0 && currentInput.dataset['prev']) {
              (document.getElementById(currentInput.dataset['prev']) as HTMLInputElement)?.focus();
            }

            // Borrar el campo de respaldo si se empieza a usar el OTP
            if (val.length > 0 && backupInput) {
              backupInput.value = '';
            }
          });
        });

        // 2. Borrar OTP si se empieza a usar el campo de respaldo
        if (backupInput) {
          backupInput.addEventListener('input', () => {
            if (backupInput.value.length > 0) {
              inputs.forEach(input => input.value = '');
            }
          });
        }

        // Enfocar el primer input al abrir el modal
        if (firstInput) {
          firstInput.focus();
        }
      },

      // --- preConfirm: Lógica de validación y recolección de datos antes de confirmar ---
      preConfirm: (): AuthResult | false => {
        const inputs = Array.from(document.querySelectorAll('.otp-input')) as HTMLInputElement[];
        const otpCode = inputs.map(input => input.value).join('');
        const backupInput: HTMLInputElement | null = document.getElementById('backup-code-input') as HTMLInputElement;
        const backupCode = backupInput ? backupInput.value : '';

        if (otpCode.length === 6) {
          // Si el OTP está completo
          return { code: otpCode, type: 'otp' };
        } else if (backupCode) {
          // Si el OTP no está completo pero hay código de respaldo
          return { code: backupCode, type: 'backup' };
        } else {
          // Si no hay código de 6 dígitos ni código de respaldo
          Swal.showValidationMessage('Please enter the 6-digit code or the backup code.');
          return false; // Evita que el modal se cierre
        }
      },

    }).then((result: SweetAlertResult<AuthResult>) => {
      // --- then: Manejo del resultado después de cerrar el modal ---
      if (result.isConfirmed && result.value) {
        // El usuario presionó 'Verify' y pasó la validación
        console.log(`Verification successful. Type: ${result.value.type}, Code: ${result.value.code}`);
        // TODO: Llama aquí a tu servicio de autenticación con result.value.code

      } else if (result.dismiss === Swal.DismissReason.cancel) {
        // El usuario presionó 'Cancel'
        console.log('Authentication canceled.');
      }
    });
  }

}
